require: rubocop-rails

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 124

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30


Rails/FilePath:
  Enabled: false