require: rubocop-rails

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 124

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 331

Metrics/AbcSize:
  Max: 23

Rails/FilePath:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false
